#version: '3.5'
#services:
#  db:
#    container_name: postgres_db
#    image: postgres:15-alpine
#    restart: always
#    environment:
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "postgres"
#      POSTGRES_DB: "voteSystem"
#    ports:
#      - "5432:5432"

